### PR TITLE
Render nostotagging on footer or top based on setting

### LINKED ISSUE #149: The hook detection (top or footer) doesn't work
The `$HOOK_TOP` is always executed regardless if it's actually rendered in a template or if it exists in a template

### PR DESCRIPTION
**Pull request by chenliangde**
Closes #149

### CODE REVIEW

File: nostotagging.php [hunk 1]
```diff
@@ -377,8 +380,11 @@ public function hookTop()
      */
     public function hookDisplayFooter()
     {
-        $html = NostoDefaultTagging::get($this);
+        $taggingOnFooter = NostoHelperConfig::getNostotaggingRenderPosition()
+            === NostoHelperConfig::NOSTOTAGGING_POSITION_FOOTER;
+        $html = $taggingOnFooter ? NostoDefaultTagging::get($this) : '';
```
Comment (mridang) [inline nostotagging.php]: Where's the if statement?
